### ISSUE TITLE
Newsletter #41

### ISSUE THREAD

**Issue by joe-rlo** [NEAR-DevHub/content#13]
### Version

41

### Tasks

- [x] Content Ready
- [x] Template Ready
- [x] Email Sent
- [x] Posted on Telegram
- [x] Posted on Discord
- [x] Posted on Twitter/X
- [x] Posted on Reddit
- [x] Posted on LinkedIn
- [x] Posted on Instagram

**Comment by PiVortex** [comment]
{Title}
Hackathons, Tools, RPCs, and more!

{Intro}
We're back again to inject you with the latest NEAR developer news! As the holidays are rapidly approaching if you're taking time away from building, don't worry we'll make sure to keep you updated with all the latest developer news so you can hit the ground running when you come back.

# News

{Include}
**REDACTED Hackathon Winners**
The winners of the REDACTED Hackathon have been announced! 🎉
After 2 months of non-stop hacking, the judges have spoken and 30 winners have been selected. Take a look at the list of these [amazing projects](https://redacted.devpost.com/project-gallery).

{Include}
**Tools Community Call #14**
The [14th Tools Community Call](https://calendar.google.com/calendar/u/0/r/eventedit/copy/MXY3bnFxZDFnM21yNTFqZmc1ZzJtaWI4dnVfMjAyNDEyMTBUMTcwMDAwWiBjX2Y1NGVkMzdmZDkyMzI3YWNkYzdlNDM0M2ZlNDA3MjJhZTU3OTdiNmM4MjkyOWJhOTNlOWYzYTg5YzY5NjU3YWJAZw/b3dlbmdlb3JnZWhhc3NhbGxAZ21haWwuY29t) will be held this Tuesday the 10th of December at 5 PM UTC. If you want to provide updates on your tools or suggest a discussion topic, please reach out in the [Tools Telegram Channel](https://t.me/NEAR_Tools_Community_Group).

{Include}
**Adjusted RPC Rate Limits**
As part of Pagoda's wind down, the free near.org RPCs are being rate-limited with the limits getting stricter each month. The limits are currently being adjusted to:
- 4000 RPM for Mainnet RPC
- 1800 RPM for Testnet RPC
- 200 RPM for Mainnet Archival RPC
- 400 RPM for Testnet Archival RPC
Find out further information in this tweet 👉 [Link](https://x.com/ekuzyakov/status/1863462531613823463?s=61).

{Include, the open open is intended}
**Race of Sloths Open Open-Source**
Race of Sloths is now public allowing you to earn sloth points by making a PR on [any open source repo](https://x.com/race_of_sloths/status/1862596893466878200?s=61).

{Include}
**DAO Agent + Matched Funding**
Community member Jass contributed a [Bitte DAO Agent](https://github.com/jaswinder6991/dao-agent-next), enabling seamless AI interactions with the Sputnik DAO contracts, scoring himself a $3k bounty which was then [matched by DevHub](https://x.com/neardevhub/status/1864376626219503861?s=61)!

{Include if it fits}
**NEAR Protocol Plugin**
Firat from Nuffle Labs has made a PR to introduce a NEAR Protocol plugin to ai16z's Eliza, a lightweight AI agent framework, to introduce capabilities such as making token swaps through Ref Finance. [Dive into the PR](https://github.com/ai16z/eliza/pull/847).

{Include if it fits}
**Virtual Chain Console**
Aurora Labs are looking for developers to help test and provide feedback for the Virtual Chain Console - their latest product created to teach developers about what they can do while developing their own EVM virtual chains on NEAR. [Sign up via this form to take part](https://docs.google.com/forms/d/e/1FAIpQLSdxg4sIWQIWPgvcQlut8SHC-2jOlrcd6xOSLbjcH10VSnFCRg/viewform).


# In case you missed it

{Include}
**Keypom FastAuth**
The Keypom team has just released the first version of Keypom FastAuth to testnet. This allows you to create an account and log in via Google, and what's more, you can integrate it into your app with just **ONE LINE OF CODE**! [Try it out for yourself and take a look at what's coming next](https://x.com/ben_kurrek/status/1861843743579701737?s=61).

{Include}
**Private DAOs**
The Calimero team have just released a private DAO example where all proposal data and discussions happen off-chain P2P between parties, but then payments are settled on-chain. If you're interested in building privacy [dive the GitHub repo](https://x.com/chefsale/status/1861387009853383102?s=61).

{Include}
**Chain Un-abstractor**
Slime has released a new repo that contains a HTTP service that indexes transactions on different chains and gets their transaction hash by their signature. This proves very useful when mapping a chain signature from the MPC to the transaction hash on the destination chain. [Check it out](https://github.com/INTEARnear/unabstract)!

# Tweets

{Include}
https://x.com/thedefisaint/status/1861695411943362681?s=46&t=sPrc7IMmwC_3Wog4EoUSRw
@thedefisaint

{Include}
https://x.com/bitteprotocol/status/1863929456131235898?s=61
@bitteprotocol

{Include}
https://x.com/ringfenceai/status/1863916684374843869?s=61
@ringfenceai

&nbsp;

# Video
{Include}
https://www.youtube.com/watch?v=u0hPVcZeb70
Omni Wallet Preview

{No quote this week}
# Quote

{Added one to in person}
# EVENTS

### Online

{semi important, reoccuring event keep in weekly if possible but small}
- DevHub Live | Every Thursday at 4PM UTC | [Add to calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=NzA2cml2bXQ2NjY0amFiczJyNGpmYWgxbWpfMjAyNDA4MDhUMTYwMDAwWiBjX2Y1NGVkMzdmZDkyMzI3YWNkYzdlNDM0M2ZlNDA3MjJhZTU3OTdiNmM4MjkyOWJhOTNlOWYzYTg5YzY5NjU3YWJAZw&tmsrc=c_f54ed37fd92327acdc7e4343fe40722ae5797b6c82929ba93e9f3a89c69657ab%40group.calendar.google.com&scp=ALL)

{semi important, reoccuring event keep in weekly if possible but small}
- Developer Office Hours | Every Thursday @ 11AM & 6PM UTC | [11AM UTC](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MWd1Y2ZkNG9jcWEybHZkdGs1Mm4yYWZrYm9fMjAyNDA4MDhUMTEwMDAwWiBjX2Y1NGVkMzdmZDkyMzI3YWNkYzdlNDM0M2ZlNDA3MjJhZTU3OTdiNmM4MjkyOWJhOTNlOWYzYTg5YzY5NjU3YWJAZw&tmsrc=c_f54ed37fd92327acdc7e4343fe40722ae5797b6c82929ba93e9f3a89c69657ab%40group.calendar.google.com&scp=ALL) & [6PM UTC](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MHFhYjAzdmR1NXFkbjVjb3BhZWY2MGtnZG9fMjAyNDA4MDhUMTgwMDAwWiBjX2Y1NGVkMzdmZDkyMzI3YWNkYzdlNDM0M2ZlNDA3MjJhZTU3OTdiNmM4MjkyOWJhOTNlOWYzYTg5YzY5NjU3YWJAZw&tmsrc=c_f54ed37fd92327acdc7e4343fe40722ae5797b6c82929ba93e9f3a89c69657ab%40group.calendar.google.com&scp=ALL)

{semi important, reoccuring event keep in weekly if possible but small, can reduce to just Youtube if too many}
- NEAR AI Office Hours | Every Tuesday 4:30 PM UTC | [Youtube](https://www.youtube.com/@NEARProtocol/videos) - [Twitter](https://x.com/NEARProtocol)

### In Person:

- [Build Europe](https://www.buidleurope.com/) | January 9 – 10, 2025 | Lisbon

If you are running a local NEAR event please register as a Hackbox host 👉 [here](https://near.org/hackbox.near/widget/home).

&nbsp;

# Resources

{important but can go lower down}
**New to NEAR?:** Check out these resources 👨‍💻
1. Docs 👉 [Link](https://docs.near.org/)
2. DevHub 👉 [Link](https://near.social/devhub.near/widget/app)
3. Developer guide 👉 [LINK](https://github.com/near)
4. Developer Telegram Group, ask any NEAR development questions 👉 [LINK](https://t.me/neardev)
5. Discord 👉 [LINK](https://discord.gg/vMGH5QywTH)
6. Office Hours, get personalized support 👉 [LINK](https://near.social/devhub.near/widget/app?page=community&handle=devrel&tab=office-hours)

{Removed Protocol rewards}
### PROJECT SUPPORT

{Important but can go lower down}
- Web3 x AI equity-free accelerator program: [HZN](https://www.hzn.xyz/)
- The NEAR Bounty Booster initiative has been launched to support hackers who use the NEAR stack in non-sponsored hackathons, by matching winnings up to $5,000. The program applies to both Web2 and Web3 Hackathons ⭐️ [Learn more](https://near.social/devhub.near/widget/app?page=blog&id=3021)

&nbsp;

### Thank you for reading, see you next week for more NEAR Dev News! 👋
