### ISSUE TITLE
Newsletter 42

### ISSUE THREAD

**Issue by joe-rlo** [NEAR-DevHub/content#14]
### Version

42

### Tasks

- [x] Content Ready
- [x] Template Ready
- [x] Email Sent
- [x] Posted on Telegram
- [x] Posted on Discord
- [x] Posted on Twitter/X
- [x] Posted on Reddit
- [x] Posted on LinkedIn
- [x] Posted on Instagram

**Comment by PiVortex** [comment]
{Title}
Unlimited Releases

{Intro}
There's a bunch of new releases in the NEAR ecosystem this week to improve your developer experience, so without further ado let's get right into the details.

# News
{Main item 1 of 2}
**Build Multichain Transactions in Contracts**
The first release of [omni-transaction-rs](https://github.com/near/omni-transaction-rs) is out! This library is used to build transactions for different chains inside of a NEAR smart contract to enable you to control accounts on other chains via smart contract logic. This allows for many use cases such as cross-chain swaps without bridging and AccountFi.

{Main item 2 of 2}
**GetBlock Infrastructure Grants**
NEAR has partnered with GetBlock to provide infrastructure support to early-stage startups building on top of NEAR. Selected startups will receive a grant for RPC requests, technical support, co-marketing opportunities and more. [Learn more here](https://getblock.io/near-startup-program/?utm_source=twitter&utm_medium=social&utm_campaign=startup).

{Include but smaller}
**Real-time Events WebSocket API**
Intear has launched a new WebSocket API to make it easier to listen for real-time events on NEAR. Check out the long list of events you can listen for [here](https://docs.intear.tech/docs/events-api/).

{Include but smaller}
**Nearcore 2.4.0**
Nearcore 2.4.0 is out! This update adds epoch sync and decentralized state sync as well as optimizations to congestion control. See the [release notes](https://github.com/near/nearcore/releases/tag/2.4.0) for more details.

{Include but smaller}
**GitHub Actions Injections via Branch Names**
Beware of GitHub actions injections via branch names. A recent security incident demonstrated how attackers can exploit GitHub actions workflows through maliciously crafted branch names, leading to unauthorized access to repository secrets. Read more in this [blog post](https://blog.yossarian.net/2024/12/06/zizmor-ultralytics-injection).

{Include but smaller}
**NEAR CLI 0.16.1**
NEAR CLI 0.16.1 introduces a nice helper to get the final CLI command executed saved in your shell history. Check out the full release notes [here](https://github.com/near/near-cli-rs/releases/tag/v0.16.1).


# In case you missed it

{Include}
**REDACTED Hackathon Winners**
The winners of the REDACTED Hackathon have been announced! 🎉
After 2 months of non-stop hacking, the judges have spoken and 30 winners have been selected. Take a look at the list of these [amazing projects](https://redacted.devpost.com/project-gallery).

{Include}
**Adjusted RPC Rate Limits**
As part of Pagoda's wind down, the free near.org RPCs are being rate-limited with the limits getting stricter each month. The limits are currently being adjusted to:
- 4000 RPM for Mainnet RPC
- 1800 RPM for Testnet RPC
- 200 RPM for Mainnet Archival RPC
- 400 RPM for Testnet Archival RPC
Find out further information in this tweet 👉 [Link](https://x.com/ekuzyakov/status/1863462531613823463?s=61).

{Lets try to make the tweets smaller as well?}
# Tweets

{Include}
https://x.com/serrrfirat/status/1866116721704075354?s=61
@serrrfirat

{Include}
https://x.com/avbnear/status/1864713959292432428?s=46&t=sPrc7IMmwC_3Wog4EoUSRw
@avbnear

{Include}
https://x.com/vgrichina/status/1858668776721707191?s=61
@vgrichina

&nbsp;

# Video
{Include}
https://www.youtube.com/watch?v=mfaPJLN5h_w
Best practices for NEAR Smart Contract Development 

{Next to video}
# Quote
"Never stop learning! There are a lot of useful resources and examples that you can take inspiration from."

{Added one to in person}
# EVENTS

### Online

{semi important, reoccuring event keep in weekly if possible but small}
- DevHub Live | Every Thursday at 4PM UTC | [Add to calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=NzA2cml2bXQ2NjY0amFiczJyNGpmYWgxbWpfMjAyNDA4MDhUMTYwMDAwWiBjX2Y1NGVkMzdmZDkyMzI3YWNkYzdlNDM0M2ZlNDA3MjJhZTU3OTdiNmM4MjkyOWJhOTNlOWYzYTg5YzY5NjU3YWJAZw&tmsrc=c_f54ed37fd92327acdc7e4343fe40722ae5797b6c82929ba93e9f3a89c69657ab%40group.calendar.google.com&scp=ALL)

{semi important, reoccuring event keep in weekly if possible but small}
- Developer Office Hours | Every Thursday @ 11AM & 6PM UTC | [11AM UTC](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MWd1Y2ZkNG9jcWEybHZkdGs1Mm4yYWZrYm9fMjAyNDA4MDhUMTEwMDAwWiBjX2Y1NGVkMzdmZDkyMzI3YWNkYzdlNDM0M2ZlNDA3MjJhZTU3OTdiNmM4MjkyOWJhOTNlOWYzYTg5YzY5NjU3YWJAZw&tmsrc=c_f54ed37fd92327acdc7e4343fe40722ae5797b6c82929ba93e9f3a89c69657ab%40group.calendar.google.com&scp=ALL) & [6PM UTC](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MHFhYjAzdmR1NXFkbjVjb3BhZWY2MGtnZG9fMjAyNDA4MDhUMTgwMDAwWiBjX2Y1NGVkMzdmZDkyMzI3YWNkYzdlNDM0M2ZlNDA3MjJhZTU3OTdiNmM4MjkyOWJhOTNlOWYzYTg5YzY5NjU3YWJAZw&tmsrc=c_f54ed37fd92327acdc7e4343fe40722ae5797b6c82929ba93e9f3a89c69657ab%40group.calendar.google.com&scp=ALL)

{semi important, reoccuring event keep in weekly if possible but small, can reduce to just Youtube if too many}
- NEAR AI Office Hours | Every Tuesday 4:30 PM UTC | [Youtube](https://www.youtube.com/@NEARProtocol/videos) - [Twitter](https://x.com/NEARProtocol)

### In Person:

- [Build Europe](https://www.buidleurope.com/) | January 9 – 10, 2025 | Lisbon

If you are running a local NEAR event please register as a Hackbox host 👉 [here](https://near.org/hackbox.near/widget/home).

&nbsp;

# Resources

{important but can go lower down}
**New to NEAR?** Check out these resources 👨‍💻
1. Docs 👉 [Link](https://docs.near.org/)
2. DevHub 👉 [Link](https://near.social/devhub.near/widget/app)
3. Developer guide 👉 [LINK](https://github.com/near)
4. Developer Telegram Group, ask any NEAR development questions 👉 [LINK](https://t.me/neardev)
5. Discord 👉 [LINK](https://discord.gg/vMGH5QywTH)
6. Office Hours, get personalized support 👉 [LINK](https://near.social/devhub.near/widget/app?page=community&handle=devrel&tab=office-hours)

{Removed Protocol rewards}
### PROJECT SUPPORT

{Important but can go lower down}
- Web3 x AI equity-free accelerator program: [HZN](https://www.hzn.xyz/)
- The NEAR Bounty Booster initiative has been launched to support hackers who use the NEAR stack in non-sponsored hackathons, by matching winnings up to $5,000. The program applies to both Web2 and Web3 Hackathons ⭐️ [Learn more](https://near.social/devhub.near/widget/app?page=blog&id=3021)

&nbsp;

### Thank you for reading, see you next week for more NEAR Dev News! 👋
